### ISSUE TITLE
Switch to pycryptodome

### ISSUE THREAD

**Issue by papachoco** [NextThought/nti.recipes.passwords#2]
Jason,

IT seems pycryptodome (https://pypi.python.org/pypi/pycryptodome) is newer and being actively maintained   (instead of PyCrypto). Plus it supports pypy

What do you think about making the switch?

Carlos

**Comment by jamadden** [comment]
If we're going to make a change, I would *strongly* recommend [cryptography](https://pypi.python.org/pypi/cryptography) instead. That's the semi-official new standard for cryptography in Python that the community is adopting.

I didn't realize this repo was public...

**Comment by jamadden** [comment]
I'll work up a PR. It shouldn't take long.

**Comment by papachoco** [comment]
awesome
